create database pedido;
use pedido;
CREATE TABLE estado(
ESTADO_CODIGO CHAR(2) PRIMARY KEY,
ESTADO_NOME VARCHAR(25) );
CREATE TABLE ue_produto(
UE_PRODUTO_COD CHAR(3),
UE_PRODUTO_DESCR VARCHAR(50));
CREATE TABLE cliente(
CLIENTE_ID INTEGER(10) PRIMARY KEY,
CLIENTE_NOME CHAR(50),
CLIENTE_END CHAR(50),
CLIENTE_END_CIDADE CHAR (20),
ESTADO_CODIGO CHAR(2),
CLIENTE_END_CEP CHAR(8),
CLIENTE_TELEFONE CHAR(10),
CLIENTE_PERC_DESCONTO DECIMAL(2,0),
FOREIGN KEY(ESTADO_CODIGO) REFERENCES estado (ESTADO_CODIGO) );
CREATE TABLE produto(
PRODUTO_CODIGO SMALLINT(6) PRIMARY KEY,
PRODUTO_NOME CHAR(40),
PRODUTO_PRECO DOUBLE(5,2),
UE_PRODUTO_COD CHAR(3),
FOREIGN KEY (UE_PRODUTO_COD) REFERENCES ue_produto (UE_PRODUTO_COD) );
CREATE TABLE pedido(
PEDIDO_IDENTIFICACAO INTEGER(11) PRIMARY KEY,
PEDIDO_TIPO ENUM('A VISTA', 'A PRAZO 30 DIAS'),
CLIENTE_ID INTEGER(10),
PEDIDO_DATA_ENTRADA DATE,
PEDIDO_VALOR_TOTAL DECIMAL(7,2),
PEDIDO_DESCONTO DECIMAL(7,2),
PEDIDO_DT_EMBARQUE DATE,
FOREIGN KEY (CLIENTE_ID) REFERENCES cliente (CLIENTE_ID) );
CREATE TABLE item(
PEDIDO_IDENTIFICACAO INTEGER,
    PRODUTO_CODIGO SMALLINT(6),
    ITEM_QUANTIDADE SMALLINT(6),
    ITEM_VALOR_UNITARIO DOUBLE(5,2),
    ITEM_VALOR_TOTAL DOUBLE(5,2),
    PRIMARY KEY (PEDIDO_IDENTIFICACAO, PRODUTO_CODIGO),
    FOREIGN KEY (PEDIDO_IDENTIFICACAO) REFERENCES pedido(PEDIDO_IDENTIFICACAO),
    FOREIGN KEY (PRODUTO_CODIGO) REFERENCES produto(PRODUTO_CODIGO)
);